App\Order\Application\Request\AddProductToCartRequest:
    properties:
        userId:
            - NotBlank: ~
            - Positive: ~
        region:
            - NotBlank: ~
            - Choice:
                callback: ['App\Order\Domain\Enum\RegionCodeEnum', 'values']
        supCode:
            - NotBlank: ~
            - Regex:
                pattern: '/^\d{15}$/'
                message: 'sup_code must be a string of 15 digits.'
        quantity:
            - NotBlank: ~
            - Positive: ~
        orderDate:
            - NotBlank: ~

App\Order\Application\Request\RemoveProductFromCartRequest:
    properties:
        userId:
            - NotBlank: ~
            - Positive: ~
        region:
            - NotBlank: ~
            - Choice:
                callback: ['App\Order\Domain\Enum\RegionCodeEnum', 'values']
        supCode:
            - NotBlank: ~
            - Regex:
                pattern: '/^\d{15}$/'
                message: 'sup_code must be a string of 15 digits.'

App\Order\Application\Request\CartSetUpRequest:
    properties:
        userId:
            - NotBlank: ~
            - Positive: ~
        region:
            - NotBlank: ~
            - Choice:
                callback: ['App\Order\Domain\Enum\RegionCodeEnum', 'values']
        orderDate:
            - NotBlank: ~
        isDelivery:
            - NotNull: ~

App\Order\Application\Request\CreateOrderRequest:
    properties:
        userId:
            - NotBlank: ~
            - Positive: ~
        region:
            - NotBlank: ~
            - Choice:
                callback: ['App\Order\Domain\Enum\RegionCodeEnum', 'values']

App\Order\Application\Request\GetCartRequest:
    properties:
        userId:
            - NotBlank: ~
            - Positive: ~
        region:
            - NotBlank: ~
            - Choice:
                callback: ['App\Order\Domain\Enum\RegionCodeEnum', 'values']
