App\Order\Application\Request\GetCartRequest:
    properties:
        userId:
            - NotBlank: ~
            - Positive: ~
        region:
            - NotBlank: ~
            - Choice:
                callback: ['App\Order\Domain\Enum\RegionCodeEnum', 'values']
